// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4NNDlaTOq7z0aL3pgHlGoC2gH5yO-6-c',
    appId: '1:463323672937:web:83dd37bbf4be0e112a0df8',
    messagingSenderId: '463323672937',
    projectId: 'migration-app-afghan',
    authDomain: 'migration-app-afghan.firebaseapp.com',
    storageBucket: 'migration-app-afghan.appspot.com',
    measurementId: 'G-4KYFF1K1X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfC6jp2ECQHGYWTrUWU4PzKBqeC53mJY',
    appId: '1:463323672937:android:6aab8e796882fcc92a0df8',
    messagingSenderId: '463323672937',
    projectId: 'migration-app-afghan',
    storageBucket: 'migration-app-afghan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR39-5EOnCCQMa322rxjr_Du4xfz0Ztro',
    appId: '1:463323672937:ios:a6656d1eabc8312b2a0df8',
    messagingSenderId: '463323672937',
    projectId: 'migration-app-afghan',
    storageBucket: 'migration-app-afghan.appspot.com',
    iosClientId: '463323672937-61dkf72g7ib2osdtjhcog49go3htrhgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR39-5EOnCCQMa322rxjr_Du4xfz0Ztro',
    appId: '1:463323672937:ios:a6656d1eabc8312b2a0df8',
    messagingSenderId: '463323672937',
    projectId: 'migration-app-afghan',
    storageBucket: 'migration-app-afghan.appspot.com',
    iosClientId: '463323672937-61dkf72g7ib2osdtjhcog49go3htrhgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
